const API='https://www.alphavantage.co/query';
const nullable=v=>v==null||v===''||v==='None'||v==='-'?null:Number.isFinite(Number(v))?Number(v):v;
async function query(params,key){const url=new URL(API);Object.entries({...params,apikey:key}).forEach(([k,v])=>url.searchParams.set(k,v));const res=await fetch(url,{signal:AbortSignal.timeout(18000)});if(!res.ok)throw new Error(`Market data provider returned ${res.status}`);const body=await res.json();if(body.Note||body.Information)throw new Error('Market data provider rate limit reached');if(body['Error Message'])throw new Error('Ticker not found.');return body}
export async function fetchAlphaVantage(ticker,key){
 if(!key)throw new Error('Live research requires ALPHA_VANTAGE_API_KEY on the server.');
 const [overview,daily,news]=await Promise.all([query({function:'OVERVIEW',symbol:ticker},key),query({function:'TIME_SERIES_DAILY',symbol:ticker,outputsize:'full'},key),query({function:'NEWS_SENTIMENT',tickers:ticker,limit:'20',sort:'LATEST'},key).catch(()=>({feed:[]}))]);
 const series=daily['Time Series (Daily)']; if(!series||!Object.keys(series).length)throw new Error('Ticker not found.');
 const history=Object.entries(series).map(([date,x])=>({date,open:+x['1. open'],high:+x['2. high'],low:+x['3. low'],close:+x['4. close'],volume:+x['5. volume']})).sort((a,b)=>a.date.localeCompare(b.date));
 const last=history.at(-1),prev=history.at(-2);
 return {overview,history,market:{price:last.close,previousClose:prev?.close??null,changePercent:prev?(last.close/prev.close-1)*100:null,asOf:`${last.date}T20:00:00Z`,high52:Math.max(...history.slice(-252).map(x=>x.high)),low52:Math.min(...history.slice(-252).map(x=>x.low)),averageVolume:null},news:(news.feed||[]).map(x=>({headline:x.title,summary:x.summary,source:x.source,date:x.time_published?.slice(0,8).replace(/(\d{4})(\d{2})(\d{2})/,'$1-$2-$3'),url:x.url})).filter(x=>x.url)};
}
export function mapOverview(o={}){return{name:o.Name||o.Symbol||'Unknown security',exchange:o.Exchange||null,sector:o.Sector||null,industry:o.Industry||null,description:o.Description||null,valuation:{trailingPE:nullable(o.TrailingPE),forwardPE:nullable(o.ForwardPE),peg:nullable(o.PEGRatio),priceToSales:nullable(o.PriceToSalesRatioTTM),priceToBook:nullable(o.PriceToBookRatio),evRevenue:nullable(o.EVToRevenue),evEbitda:nullable(o.EVToEBITDA)},fundamentals:{marketCap:nullable(o.MarketCapitalization),revenueTTM:nullable(o.RevenueTTM),epsTTM:nullable(o.EPS),revenueGrowth:nullable(o.QuarterlyRevenueGrowthYOY),epsGrowth:nullable(o.QuarterlyEarningsGrowthYOY),grossMargin:nullable(o.GrossProfitTTM)&&nullable(o.RevenueTTM)?nullable(o.GrossProfitTTM)/nullable(o.RevenueTTM)*100:null,operatingMargin:nullable(o.OperatingMarginTTM)*100,netMargin:nullable(o.ProfitMargin)*100,roe:nullable(o.ReturnOnEquityTTM)*100,dividendYield:nullable(o.DividendYield)*100,nextEarningsDate:o.LatestQuarter||null}}}
