import {fetchYahoo} from './provider.js';
import {classify} from './classifier.js';
import {calculateTechnicals,returns} from './indicators.js';
import {getReport,saveReport,historyDates} from './storage.js';
const round=v=>Number.isFinite(v)?Number(v.toFixed(2)):null;
export function normalizeTicker(raw){const ticker=String(raw||'').trim().toUpperCase();if(!/^[A-Z0-9][A-Z0-9.-]{0,11}$/.test(ticker))throw new Error('Ticker not found.');return ticker}
function metricScore(value,good,bad,invert=false){if(value==null)return 50;const x=Math.max(0,Math.min(100,(value-bad)/(good-bad)*100));return invert?100-x:x}
function rate(c,v,t){let score;if(c.leveraged)score=.25*metricScore(t.rsi14,60,30)+.2*metricScore(v.forwardPE,20,45)+.2*metricScore(t.realizedVolatility,35,100)+.2*metricScore(t.drawdownFromHigh,-5,-45)+15;else if(c.category==='ETF')score=.3*metricScore(v.forwardPE,20,45)+.25*metricScore(v.peg,1,3)+.25*metricScore(t.rsi14,60,30)+20;else score=.25*metricScore(v.forwardPE,18,45)+.2*metricScore(v.peg,1,3)+.2*metricScore(t.rsi14,60,30)+35;score=Math.round(Math.max(0,Math.min(100,score)));const rating=score>=85?'STRONG BUY':score>=70?'BUY':score>=45?'HOLD':score>=30?'SELL':'STRONG SELL';return{score,rating}}
function compare(now,prev){if(!prev)return[];const pairs=[['Price',prev.market.price,now.market.price,'Market price changed.'],['Forward P/E',prev.valuation.forwardPE,now.valuation.forwardPE,'Price and/or forward earnings estimates changed.'],['PEG',prev.valuation.peg,now.valuation.peg,'Valuation or expected growth changed.'],['Rating',prev.recommendation.rating,now.recommendation.rating,'The weighted model score crossed a configured threshold.'],['RSI (14)',prev.technicals.rsi14,now.technicals.rsi14,'Recent price momentum changed.']];return pairs.filter(([,a,b])=>a!=null&&b!=null&&String(a)!==String(b)).map(([label,a,b,reason])=>({label,before:typeof a==='number'?round(a):a,after:typeof b==='number'?round(b):b,reason}))}
export async function buildResearch(raw,{force=false,triggerType='public_search'}={}){
 const ticker=normalizeTicker(raw),cached=await getReport(ticker);const ttl=(Number(process.env.CACHE_TTL_MINUTES)||30)*60000;if(!force&&cached&&Date.now()-Date.parse(cached.generatedAt)<ttl)return{...cached,cacheHit:true};
 const data=await fetchYahoo(ticker),mapped={name:data.overview.Name,exchange:data.overview.Exchange,valuation:data.valuation,fundamentals:data.fundamentals},classification=classify(ticker,data.overview),technicals=calculateTechnicals(data.history);let valuation={...mapped.valuation};
 let holdings=data.holdings||[],portfolio={coverage:0,excludedWeight:100};
 if(classification.category==='ETF'&&holdings.length){const covered=holdings.filter(h=>h.weight>0&&h.price>0&&h.trailingEps>0),forward=holdings.filter(h=>h.weight>0&&h.price>0&&h.forwardEps>0),coverage=covered.reduce((a,h)=>a+h.weight,0),forwardCoverage=forward.reduce((a,h)=>a+h.weight,0),ey=covered.reduce((a,h)=>a+(h.weight/100)*(h.trailingEps/h.price),0),fey=forward.reduce((a,h)=>a+(h.weight/100)*(h.forwardEps/h.price),0),growthWeight=forward.filter(h=>h.epsGrowth>0).reduce((a,h)=>a+h.weight,0),growth=forward.filter(h=>h.epsGrowth>0).reduce((a,h)=>a+h.weight*h.epsGrowth,0)/(growthWeight||1);valuation={...valuation,trailingPE:ey>0?(coverage/100)/ey:valuation.trailingPE,forwardPE:fey>0?(forwardCoverage/100)/fey:valuation.forwardPE,peg:fey>0&&growth>0?((forwardCoverage/100)/fey)/growth:valuation.peg};portfolio={coverage:round(Math.max(coverage,forwardCoverage)),excludedWeight:round(100-Math.max(coverage,forwardCoverage)),forwardCoverage:round(forwardCoverage),method:'Weighted positive earnings yield over covered holdings'}}
 const rr=rate(classification,valuation,technicals);const confidence=['trailingPE','forwardPE','peg'].filter(k=>valuation[k]!=null).length>=2&&data.history.length>=200?'Moderate':'Low';
 const recommendation={...rr,confidence,horizon:classification.leveraged?'Days to weeks':'6–18 months',thesis:classification.leveraged?`A tactical ${rr.rating.toLowerCase()} based on underlying valuation, trend and realized volatility; daily-reset path risk remains central.`:`A ${rr.rating.toLowerCase()} based on available valuation and technical evidence. The score is constrained where estimates or portfolio data are absent.`,catalyst:classification.leveraged?'Persistent underlying index momentum with contained volatility.':'Earnings delivery and improving forward estimates.',risk:classification.leveraged?'Volatility decay, sharp drawdown and BMO issuer credit exposure.':'Estimate cuts, valuation compression or weakening price trend.',upgrade:'Improving estimates, valuation and trend alignment.',downgrade:'Estimate deterioration or a sustained technical breakdown.'};
 const price=data.market.price;const scenarioPct=classification.leveraged?[-30,0,35]:[-20,10,30];const scenarios=['Bear','Base','Bull'].map((name,i)=>({name,range:price?`$${round(price*(1+scenarioPct[i]/100)*.95)}–$${round(price*(1+scenarioPct[i]/100)*1.05)}`:'Unavailable',assumptions:classification.leveraged?`${scenarioPct[i]}% path-sensitive tactical outcome; volatility and daily compounding can materially change results.`:`Illustrative ${scenarioPct[i]}% midpoint outcome using broad multiple and earnings sensitivity; not false-precision intrinsic value.`}));
 const generatedAt=new Date().toISOString(),reportDate=generatedAt.slice(0,10);const notes=[];if(!data.market.price)notes.push('Price unavailable.');if(classification.category!=='STOCK'&&!holdings.length)notes.push('Issuer holdings/index adapter is not configured; portfolio values are withheld.');if(valuation.forwardPE==null)notes.push('Forward estimate coverage is unavailable.');if(classification.category==='ETF'&&portfolio.coverage<50)notes.push(`Look-through coverage is limited to ${portfolio.coverage}% of portfolio weight.`);
 let report={ticker,name:mapped.name,exchange:mapped.exchange,classification,market:data.market,valuation,fundamentals:mapped.fundamentals,fund:data.fund,technicals,history:data.history.slice(-300),holdings,portfolio,news:data.news,etfAnalysis:classification.category==='ETF'?{earningsEngine:holdings.length?`The displayed holdings cover ${portfolio.coverage}% of portfolio weight. High-weight holdings with positive expected EPS growth contribute most; uncovered holdings are excluded rather than assumed.`:'Constituent earnings contribution requires a current holdings feed.',valuationDrivers:holdings.length?'Holdings with high weights and high forward multiples raise portfolio valuation; positive-earnings holdings with lower multiples reduce it. Coverage is displayed beside the calculation.':'Portfolio valuation drivers are withheld until verified holdings coverage is available.'}:null,leverage:classification.leveraged?{actual5d:round(returns(data.history,5)),simple3x5d:null,trackingGap5d:null,effectiveLeverage:null,explanation:'FNGU resets exposure daily. A verified FANG+ total-return series is required for a defensible tracking comparison; missing values are not inferred.',decayExplanation:'Two paths with the same ending index level can produce different leveraged returns: alternating gains and losses shrink the compounding base, while a smooth trend can create favorable compounding.'}:null,scenarios,recommendation,dataQuality:{status:notes.length>1?'DEGRADED':notes.length?'PARTIAL':'GOOD',notes},sources:[{name:'Yahoo Finance',purpose:'Quotes, daily history, fundamentals, estimates, news and fund summary data',asOf:reportDate,url:`https://finance.yahoo.com/quote/${ticker}/`},{name:'Issuer / index provider',purpose:'Primary reference for fund structure and official portfolio data',asOf:reportDate,url:ticker==='CHAT'?'https://www.roundhillinvestments.com/etf/chat/':ticker==='FNGU'?'https://www.bmoetns.com/ETN/FNGU.P/':'https://www.sec.gov/edgar/search/'}],generatedAt,reportDate,triggerType,cacheHit:false};
 report.changes=compare(report,cached);await saveReport(report);report.historyDates=await historyDates(ticker);return report;
}
