import { createClient } from '@supabase/supabase-js';
import { getStore } from '@netlify/blobs';
const memory=new Map();
function client(){return process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}}):null}
const blobsEnabled=()=>Boolean(process.env.NETLIFY||process.env.NETLIFY_SITE_ID);
const store=()=>getStore({name:'research-reports',consistency:'strong'});
const key=(ticker,date)=>`reports/${ticker}/${date}`;
async function blobReports(prefix='reports/'){const {blobs}=await store().list({prefix});return Promise.all(blobs.map(x=>store().get(x.key,{type:'json',consistency:'strong'})))}
export async function saveReport(report){const c=client();if(c){const {error}=await c.from('reports').upsert({ticker:report.ticker,report_date:report.reportDate,generated_at:report.generatedAt,trigger_type:report.triggerType,data_quality:report.dataQuality.status,payload:report},{onConflict:'ticker,report_date'});if(error)throw error}else if(blobsEnabled())await store().setJSON(key(report.ticker,report.reportDate),report);else memory.set(`${report.ticker}:${report.reportDate}`,report)}
export async function getReport(ticker,date){const c=client();if(c){let q=c.from('reports').select('payload').eq('ticker',ticker);q=date?q.eq('report_date',date):q.order('generated_at',{ascending:false}).limit(1);const {data,error}=await q.maybeSingle();if(error)throw error;return data?.payload||null}if(blobsEnabled()){if(date)return await store().get(key(ticker,date),{type:'json',consistency:'strong'});const reports=await blobReports(`reports/${ticker}/`);return reports.filter(Boolean).sort((a,b)=>b.generatedAt.localeCompare(a.generatedAt))[0]||null}return date?memory.get(`${ticker}:${date}`)||null:[...memory.values()].filter(x=>x.ticker===ticker).sort((a,b)=>b.generatedAt.localeCompare(a.generatedAt))[0]||null}
export async function listReports(limit=12){const c=client();let reports;if(c){const {data,error}=await c.from('reports').select('ticker,generated_at,payload').order('generated_at',{ascending:false}).limit(limit);if(error)throw error;return data.map(x=>({ticker:x.ticker,name:x.payload.name,rating:x.payload.recommendation.rating,generatedAt:x.generated_at}))}reports=blobsEnabled()?await blobReports():[...memory.values()];return reports.filter(Boolean).sort((a,b)=>b.generatedAt.localeCompare(a.generatedAt)).slice(0,limit).map(x=>({ticker:x.ticker,name:x.name,rating:x.recommendation.rating,generatedAt:x.generatedAt}))}
export async function historyDates(ticker){const c=client();if(c){const {data}=await c.from('reports').select('report_date').eq('ticker',ticker).order('report_date',{ascending:false}).limit(30);return(data||[]).map(x=>x.report_date)}const reports=blobsEnabled()?await blobReports(`reports/${ticker}/`):[...memory.values()].filter(x=>x.ticker===ticker);return reports.filter(Boolean).map(x=>x.reportDate).sort().reverse().slice(0,30)}
