create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  ticker text not null check (ticker ~ '^[A-Z0-9][A-Z0-9.-]{0,11}$'),
  report_date date not null,
  generated_at timestamptz not null default now(),
  trigger_type text not null,
  data_quality text not null check (data_quality in ('GOOD','PARTIAL','DEGRADED')),
  payload jsonb not null,
  unique (ticker, report_date)
);
create index if not exists reports_ticker_generated_idx on public.reports(ticker, generated_at desc);
alter table public.reports enable row level security;
-- Server uses a service-role key; no public table policy is intentionally created.
