import { useEffect, useMemo, useState } from 'react';
import { PriceChart, BarChart } from './components/Charts.jsx';

const money = (v,currency='USD',locale=currency==='INR'?'en-IN':'en-US') => v == null ? '—' : new Intl.NumberFormat(locale,{style:'currency',currency,maximumFractionDigits:2}).format(v);
const compactMoney = (v,currency='USD',locale=currency==='INR'?'en-IN':'en-US') => v == null ? '—' : new Intl.NumberFormat(locale,{style:'currency',currency,notation:'compact',maximumFractionDigits:2}).format(v);
const num = (v, suffix='') => v == null || Number.isNaN(v) ? '—' : `${Number(v).toFixed(2)}${suffix}`;
const pct = v => num(v, '%');
const cleanTicker = value => value.toUpperCase().trim().replace(/[^A-Z0-9.-]/g,'').slice(0,12);

function Metric({label,value,detail}) { return <div className="metric"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div> }
function Badge({children,tone=''}) { return <span className={`badge ${tone}`}>{children}</span> }

function Home({navigate}) {
  const [ticker,setTicker]=useState(''); const [recent,setRecent]=useState([]); const [suggestions,setSuggestions]=useState([]); const [searching,setSearching]=useState(false); const [open,setOpen]=useState(false); const [active,setActive]=useState(-1);
  useEffect(()=>{ fetch('/api/recent').then(r=>r.ok?r.json():[]).then(setRecent).catch(()=>{}); },[]);
  useEffect(()=>{const q=ticker.trim();if(!q){setSuggestions([]);setSearching(false);return}const controller=new AbortController(),timer=setTimeout(()=>{setSearching(true);fetch(`/api/search?q=${encodeURIComponent(q)}`,{signal:controller.signal}).then(r=>r.ok?r.json():[]).then(x=>{setSuggestions(x);setOpen(true);setActive(-1)}).catch(e=>{if(e.name!=='AbortError')setSuggestions([])}).finally(()=>setSearching(false))},220);return()=>{clearTimeout(timer);controller.abort()}},[ticker]);
  const choose=s=>{setTicker(s.symbol);setOpen(false);navigate(`/ticker/${encodeURIComponent(s.symbol)}`)};
  const submit=e=>{e.preventDefault();if(active>=0&&suggestions[active])return choose(suggestions[active]);const exact=suggestions.find(s=>s.symbol===ticker.trim().toUpperCase())||suggestions[0];if(exact)return choose(exact);const t=cleanTicker(ticker);if(t)navigate(`/ticker/${encodeURIComponent(t)}`)};
  const keys=e=>{if(!open||!suggestions.length)return;if(e.key==='ArrowDown'){e.preventDefault();setActive(x=>Math.min(x+1,suggestions.length-1))}else if(e.key==='ArrowUp'){e.preventDefault();setActive(x=>Math.max(x-1,0))}else if(e.key==='Escape'){setOpen(false)}else if(e.key==='Enter'&&active>=0){e.preventDefault();choose(suggestions[active])}};
  return <main>
    <section className="hero"><p className="eyebrow">U.S. + INDIA · AUTOMATED PUBLIC RESEARCH</p><h1>Research Any Stock, ETF, or ETN</h1><p>Search by company name or ticker across American, NSE, and BSE listings. Evidence-first valuation, fundamentals, technicals and news—with uncertainty kept visible.</p>
      <div className="search-shell"><form className="search" onSubmit={submit}><input value={ticker} onChange={e=>{setTicker(e.target.value);setOpen(true)}} onFocus={()=>suggestions.length&&setOpen(true)} onKeyDown={keys} placeholder="Company or ticker — Netflix, RELIANCE, NFLX, TCS.NS" aria-label="Company name or ticker" role="combobox" aria-autocomplete="list" aria-expanded={open&&suggestions.length>0} aria-controls="security-suggestions" aria-activedescendant={active>=0?`suggestion-${active}`:undefined}/><button>{searching?'Searching…':'Research'} <span>→</span></button></form>
      {open&&suggestions.length>0&&<div className="suggestions" id="security-suggestions" role="listbox">{suggestions.map((s,i)=><button type="button" id={`suggestion-${i}`} role="option" aria-selected={active===i} className={active===i?'active':''} key={s.symbol} onClick={()=>choose(s)} onMouseDown={e=>e.preventDefault()}><span className="suggestion-symbol">{s.symbol}</span><span className="suggestion-name">{s.name}<small>{s.exchange} · {s.type}</small></span><span className={`market-tag ${s.market==='India'?'india':''}`}>{s.market==='India'?'🇮🇳 INDIA':'🇺🇸 U.S.'}</span></button>)}</div>}
      {open&&ticker.trim()&&!searching&&!suggestions.length&&<div className="suggestions no-results">No matching U.S., NSE, or BSE securities found.</div>}</div>
    </section>
    <section><div className="section-title"><div><p className="eyebrow">7:00 AM ET · DAILY</p><h2>Default Daily Research</h2></div></div><div className="cards">{['CHAT','FNGU'].map((t,i)=><button className="feature-card" onClick={()=>navigate(`/ticker/${t}`)} key={t}><div><Badge tone={i?'amber':'blue'}>{i?'LEVERAGED ETN':'ACTIVE ETF'}</Badge><span className="arrow">↗</span></div><h3>{t}</h3><p>{i?'3× daily FANG+ exposure, evaluated tactically.':'AI portfolio look-through and earnings engine.'}</p></button>)}</div></section>
    <section><div className="section-title"><div><p className="eyebrow">DISCOVERY</p><h2>Recently Researched</h2></div></div>{recent.length?<div className="recent">{recent.map(r=><button key={r.ticker} onClick={()=>navigate(`/ticker/${r.ticker}`)}><b>{r.ticker}</b><span>{r.name}</span><Badge>{r.rating}</Badge><small>{new Date(r.generatedAt).toLocaleString()}</small></button>)}</div>:<div className="empty">No reports yet. Search a ticker to create the first one.</div>}</section>
  </main>
}

function Report({ticker,date,navigate}) {
  const [state,setState]=useState({loading:true});
  const [refreshing,setRefreshing]=useState(false);
  const load=async(force=false)=>{setRefreshing(force);setState(s=>({...s,loading:!force,error:null}));try{const q=new URLSearchParams({ticker,...(date?{date}:{}),...(force?{refresh:'true'}:{})});const r=await fetch(`/api/research?${q}`,{method:force?'POST':'GET'});const body=await r.json();if(!r.ok)throw new Error(body.error||'Research failed');setState({loading:false,data:body});}catch(e){setState({loading:false,error:e.message});}finally{setRefreshing(false)}};
  useEffect(()=>{load()},[ticker,date]);
  if(state.loading)return <main className="loading"><div className="pulse"/><h2>Building {ticker} research</h2><p>Checking cache, market data and security-specific analytics…</p></main>;
  if(state.error)return <main><div className="error"><Badge tone="red">UNAVAILABLE</Badge><h2>{state.error}</h2><p>No figures have been inferred. Search by company name to select a supported U.S., NSE, or BSE listing.</p><button onClick={()=>navigate('/')}>Back to search</button></div></main>;
  const r=state.data; const tech=r.technicals||{}; const val=r.valuation||{}; const isFund=r.classification.category!=='STOCK';
  return <main className="report">
    <section className="report-head"><div><div className="crumb"><button onClick={()=>navigate('/')}>Research</button><span>/</span><span>{r.ticker}</span></div><div className="title-row"><h1>{r.ticker}</h1><div><h2>{r.name}</h2><p>{r.exchange||'—'} · {r.market.country||'United States'} · {r.classification.label}</p></div></div></div><button className="secondary" onClick={()=>load(true)} disabled={refreshing}>{refreshing?'Refreshing…':'↻ Refresh analysis'}</button></section>
    <section className="summary-grid"><div className="price-block"><p className="eyebrow">LAST PRICE · {r.market.currency}</p><strong>{money(r.market.price,r.market.currency,r.market.locale)}</strong><span className={(r.market.changePercent||0)>=0?'positive':'negative'}>{pct(r.market.changePercent)} today</span><small>As of {new Date(r.market.asOf).toLocaleString(r.market.locale)}</small></div><div className="rating-block"><p className="eyebrow">MODEL RATING · {r.recommendation.score}/100</p><strong className={`rating ${r.recommendation.rating.replaceAll(' ','-').toLowerCase()}`}>{r.recommendation.rating}</strong><p>{r.recommendation.confidence} confidence · {r.recommendation.horizon}</p></div><Metric label={isFund?'Look-through P/E':'Trailing P/E'} value={num(val.trailingPE,'×')} detail={val.trailingPE?'Reported/calculated as labeled':'Not available'}/><Metric label="Forward P/E" value={num(val.forwardPE,'×')}/><Metric label="PEG" value={num(val.peg,'×')}/><Metric label="Data quality" value={r.dataQuality.status} detail={r.dataQuality.notes[0]||'Validated'}/></section>
    {r.dataQuality.status!=='GOOD'&&<div className="notice"><b>{r.dataQuality.status} coverage.</b> {r.dataQuality.notes.join(' ')}</div>}
    <div className="layout"><div className="primary">
      <Section title="Recommendation" kicker="MODEL OUTPUT"><p className="lead">{r.recommendation.thesis}</p><div className="two-col"><Callout label="Key catalyst" text={r.recommendation.catalyst}/><Callout label="Key risk" text={r.recommendation.risk}/><Callout label="Upgrade trigger" text={r.recommendation.upgrade}/><Callout label="Downgrade trigger" text={r.recommendation.downgrade}/></div></Section>
      <Section title="What Changed Since Yesterday?" kicker="STRUCTURED COMPARISON">{r.changes.length?r.changes.map((c,i)=><div className="change" key={i}><b>{c.label}</b><span>{c.before} → {c.after}</span><p>{c.reason}</p></div>):<p className="muted">No prior daily snapshot is available for comparison.</p>}</Section>
      <Section title="Valuation & Fundamentals" kicker={r.market.country==='India'?'INDIAN MARKET FUNDAMENTALS':'FUNDAMENTAL SNAPSHOT'}><div className="fund-grid"><Metric label="Market cap" value={compactMoney(r.fundamentals.marketCap,r.market.currency,r.market.locale)}/><Metric label="Price / book" value={num(val.priceToBook,'×')}/><Metric label="Price / sales" value={num(val.priceToSales,'×')}/><Metric label="EPS (TTM)" value={money(r.fundamentals.epsTTM,r.market.currency,r.market.locale)}/><Metric label="Revenue growth" value={pct(r.fundamentals.revenueGrowth)}/><Metric label="EPS growth" value={pct(r.fundamentals.epsGrowth)}/><Metric label="ROE" value={pct(r.fundamentals.roe)}/><Metric label="Debt / equity" value={num(r.fundamentals.debtToEquity)}/><Metric label="Dividend yield" value={pct(r.fundamentals.dividendYield)}/><Metric label="Free cash flow" value={compactMoney(r.fundamentals.freeCashFlow,r.market.currency,r.market.locale)}/></div>{r.market.country==='India'&&<p className="caption">Values are reported in Indian rupees where monetary. NSE and BSE listings may differ in liquidity while representing the same issuer; select the intended listing from search.</p>}</Section>
      <Section title="Price & Trend" kicker="TECHNICAL ANALYSIS"><PriceChart data={r.history}/><div className="metric-strip"><Metric label="SMA 20" value={money(tech.sma20,r.market.currency,r.market.locale)}/><Metric label="SMA 50" value={money(tech.sma50,r.market.currency,r.market.locale)}/><Metric label="SMA 200" value={money(tech.sma200,r.market.currency,r.market.locale)}/><Metric label="RSI (14)" value={num(tech.rsi14)}/><Metric label="Realized vol." value={pct(tech.realizedVolatility)}/><Metric label="Drawdown" value={pct(tech.drawdownFromHigh)}/></div><p>{tech.interpretation}</p></Section>
      {r.holdings?.length>0&&<Section title={r.classification.leveraged?'Underlying Constituents':'Holdings'} kicker={r.classification.leveraged?'NYSE FANG+ LAYER':'PORTFOLIO LOOK-THROUGH'}><BarChart data={r.holdings.slice(0,10)}/><div className="table-wrap"><table><thead><tr><th>Ticker</th><th>Name</th><th>Weight</th><th>P/E</th><th>Forward P/E</th></tr></thead><tbody>{r.holdings.slice(0,20).map(h=><tr key={h.ticker}><td><b>{h.ticker}</b></td><td>{h.name}</td><td>{pct(h.weight)}</td><td>{num(h.trailingPE,'×')}</td><td>{num(h.forwardPE,'×')}</td></tr>)}</tbody></table></div><p className="caption">Coverage: {pct(r.portfolio?.coverage)} · excluded weight: {pct(r.portfolio?.excludedWeight)}. Negative or missing earnings are excluded and disclosed, never converted to zero.</p></Section>}
      {r.etfAnalysis&&<><Section title="ETF Earnings Engine" kicker="GROWTH CONTRIBUTION"><p>{r.etfAnalysis.earningsEngine}</p></Section><Section title="ETF Valuation Drivers" kicker="PORTFOLIO FACTORS"><p>{r.etfAnalysis.valuationDrivers}</p></Section></>}
      {r.leverage&&<><Section title="Leverage Tracking & Compounding" kicker="3× DAILY RESET"><div className="metric-strip"><Metric label="5D actual" value={pct(r.leverage.actual5d)}/><Metric label="5D simple 3×" value={pct(r.leverage.simple3x5d)}/><Metric label="Tracking gap" value={pct(r.leverage.trackingGap5d)}/><Metric label="Effective leverage" value={num(r.leverage.effectiveLeverage,'×')}/></div><p>{r.leverage.explanation}</p></Section><Section title="Volatility Decay" kicker="PATH DEPENDENCY"><p>{r.leverage.decayExplanation}</p></Section></>}
      <Section title={r.classification.leveraged?'Tactical Scenarios':'Bear / Base / Bull'} kicker="SCENARIO ANALYSIS"><div className="scenario-grid">{r.scenarios.map(s=><article key={s.name} className={s.name.toLowerCase()}><span>{s.name}</span><strong>{s.range}</strong><p>{s.assumptions}</p></article>)}</div></Section>
      <Section title="Latest News" kicker="RECENT DEVELOPMENTS">{r.news.length?r.news.map(n=><a className="news" href={n.url} target="_blank" rel="noreferrer" key={n.url}><div><b>{n.headline}</b><p>{n.summary}</p></div><span>{n.source}<small>{n.date}</small></span></a>):<p className="muted">No verified recent news was returned by the configured provider.</p>}</Section>
      <Section title="Sources" kicker="DATA LINEAGE"><div className="sources">{r.sources.map(s=><a href={s.url} target="_blank" rel="noreferrer" key={s.url}><b>{s.name}</b><span>{s.purpose}</span><small>As of {s.asOf}</small></a>)}</div></Section>
    </div><aside><div className="sticky"><p className="eyebrow">REPORT INDEX</p>{['Recommendation','What Changed','Price & Trend',r.holdings?.length?'Holdings':null,r.leverage?'Leverage':null,'Scenarios','Latest News','Sources'].filter(Boolean).map(x=><span key={x}>{x}</span>)}<hr/><b>Historical reports</b>{r.historyDates?.map(d=><button key={d} onClick={()=>navigate(`/ticker/${r.ticker}/${d}`)}>{d}</button>)}</div></aside></div>
    <div className="disclaimer">Automated research may be incomplete or delayed. Ratings are model-generated, not investment advice. Leveraged products involve substantial risk. Past performance does not guarantee future results.</div>
  </main>
}
function Section({title,kicker,children}) { return <section className="panel"><p className="eyebrow">{kicker}</p><h2>{title}</h2>{children}</section> }
function Callout({label,text}) { return <div className="callout"><span>{label}</span><p>{text}</p></div> }

export default function App(){
 const [path,setPath]=useState(location.pathname); const navigate=p=>{history.pushState({},'',p);setPath(p);scrollTo(0,0)};
 useEffect(()=>{const fn=()=>setPath(location.pathname);addEventListener('popstate',fn);return()=>removeEventListener('popstate',fn)},[]);
 const route=useMemo(()=>path.match(/^\/ticker\/([A-Z0-9.-]+)(?:\/(\d{4}-\d{2}-\d{2}))?$/i),[path]);
 return <><header><button className="brand" onClick={()=>navigate('/')}><span>SD</span><div><b>Signal Desk</b><small>PUBLIC MARKET RESEARCH</small></div></button><nav><button onClick={()=>navigate('/')}>Research</button><a href="/methodology.html">Methodology</a><Badge tone="green">SYSTEMATIC · SOURCED</Badge></nav></header>{route?<Report ticker={route[1].toUpperCase()} date={route[2]} navigate={navigate}/>:<Home navigate={navigate}/>}<footer><b>Signal Desk</b><span>Automated, source-aware market research.</span><a href="/methodology.html">Methodology & limitations</a></footer></>;
}
